sudo: required
services:
  - docker

before_install:
  - docker build -t fjplaurr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fjplaurr/react-test npm test

after_success:
  - docker build -t fjplaurr/multi-client ./client
  - docker build -t fjplaurr/multi-nginx ./nginx
  - docker build -t fjplaurr/multi-server ./server
  - docker build -t fjplaurr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push those images to docker hub
  - docker push fjplaurr/multi-client
  - docker push fjplaurr/multi-nginx
  - docker push fjplaurr/multi-server
  - docker push fjplaurr/multi-worker